# Dockerfile
FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Ensure models directory exists inside the container
RUN mkdir -p models

# Default command for the container
CMD ["python", "src/predict.py"]