# .github/workflows/ci.yml
name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - docker_ci # Only run on pushes to the docker_ci branch

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run train.py to generate model files
      # This step ensures the model files are present for Docker build
      run: python src/train.py

    - name: Build Docker image
      run: docker build -t mlops-assignment-image .

    - name: Run Docker container and verify predict.py
      # This command runs predict.py inside the container.
      # If predict.py exits with an error (e.g., model not found), this job will fail.
      run: docker run mlops-assignment-image python src/predict.py

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: build_and_test_container # This job runs only if the build_and_test_container job succeeds
    if: success() # Ensures previous job completed successfully
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} # Use access token for security

    - name: Build Docker image (for tagging and push)
      # Tag with your Docker Hub username and image name
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-assignment:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mlops-assignment:latest
